---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: fix-byte-order-marker

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
    - id: gitlint

